package com.subastas.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Subasta service. Represents a row in the &quot;Subastas&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.subastas.model.impl.SubastaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.subastas.model.impl.SubastaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Subasta
 * @see com.subastas.model.impl.SubastaImpl
 * @see com.subastas.model.impl.SubastaModelImpl
 * @generated
 */
public interface SubastaModel extends BaseModel<Subasta> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a subasta model instance should use the {@link Subasta} interface instead.
     */

    /**
     * Returns the primary key of this subasta.
     *
     * @return the primary key of this subasta
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this subasta.
     *
     * @param primaryKey the primary key of this subasta
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the ID of this subasta.
     *
     * @return the ID of this subasta
     */
    public long getId();

    /**
     * Sets the ID of this subasta.
     *
     * @param id the ID of this subasta
     */
    public void setId(long id);

    /**
     * Returns the group ID of this subasta.
     *
     * @return the group ID of this subasta
     */
    public long getGroupId();

    /**
     * Sets the group ID of this subasta.
     *
     * @param groupId the group ID of this subasta
     */
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this subasta.
     *
     * @return the company ID of this subasta
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this subasta.
     *
     * @param companyId the company ID of this subasta
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this subasta.
     *
     * @return the user ID of this subasta
     */
    public long getUserId();

    /**
     * Sets the user ID of this subasta.
     *
     * @param userId the user ID of this subasta
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this subasta.
     *
     * @return the user uuid of this subasta
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this subasta.
     *
     * @param userUuid the user uuid of this subasta
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the create date of this subasta.
     *
     * @return the create date of this subasta
     */
    public Date getCreateDate();

    /**
     * Sets the create date of this subasta.
     *
     * @param createDate the create date of this subasta
     */
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this subasta.
     *
     * @return the modified date of this subasta
     */
    public Date getModifiedDate();

    /**
     * Sets the modified date of this subasta.
     *
     * @param modifiedDate the modified date of this subasta
     */
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the producto of this subasta.
     *
     * @return the producto of this subasta
     */
    @AutoEscape
    public String getProducto();

    /**
     * Sets the producto of this subasta.
     *
     * @param producto the producto of this subasta
     */
    public void setProducto(String producto);

    /**
     * Returns the estado of this subasta.
     *
     * @return the estado of this subasta
     */
    @AutoEscape
    public String getEstado();

    /**
     * Sets the estado of this subasta.
     *
     * @param estado the estado of this subasta
     */
    public void setEstado(String estado);

    /**
     * Returns the puja inicial of this subasta.
     *
     * @return the puja inicial of this subasta
     */
    public double getPujaInicial();

    /**
     * Sets the puja inicial of this subasta.
     *
     * @param pujaInicial the puja inicial of this subasta
     */
    public void setPujaInicial(double pujaInicial);

    /**
     * Returns the puja maxima of this subasta.
     *
     * @return the puja maxima of this subasta
     */
    public double getPujaMaxima();

    /**
     * Sets the puja maxima of this subasta.
     *
     * @param pujaMaxima the puja maxima of this subasta
     */
    public void setPujaMaxima(double pujaMaxima);

    /**
     * Returns the pujador ID of this subasta.
     *
     * @return the pujador ID of this subasta
     */
    public long getPujadorId();

    /**
     * Sets the pujador ID of this subasta.
     *
     * @param pujadorId the pujador ID of this subasta
     */
    public void setPujadorId(long pujadorId);

    /**
     * Returns the pujador name of this subasta.
     *
     * @return the pujador name of this subasta
     */
    @AutoEscape
    public String getPujadorName();

    /**
     * Sets the pujador name of this subasta.
     *
     * @param pujadorName the pujador name of this subasta
     */
    public void setPujadorName(String pujadorName);

    /**
     * Returns the fecha fin of this subasta.
     *
     * @return the fecha fin of this subasta
     */
    public Date getFechaFin();

    /**
     * Sets the fecha fin of this subasta.
     *
     * @param fechaFin the fecha fin of this subasta
     */
    public void setFechaFin(Date fechaFin);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.subastas.model.Subasta subasta);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.subastas.model.Subasta> toCacheModel();

    @Override
    public com.subastas.model.Subasta toEscapedModel();

    @Override
    public com.subastas.model.Subasta toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
