CREATE TABLE PRODUCTOS
(
ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
NOMBRE VARCHAR(100),
DESCRIPCION VARCHAR(100),
CONSTRAINT PRODUCTOS_PK PRIMARY KEY (ID)
);

CREATE TABLE SUBASTAS
(
ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
ID_SUBASTADOR BIGINT NOT NULL,
FECHA_INICIO TIMESTAMP NOT NULL,
FECHA_FIN TIMESTAMP NOT NULL,
ID_PRODUCTO INTEGER NOT NULL,
ESTADO VARCHAR(100),
CONSTRAINT SUBASTAS_PK PRIMARY KEY (ID),
CONSTRAINT PRODUCTO_FK FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS (ID)
);

CREATE TABLE PUJAS
(
ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
ID_PUJADOR BIGINT NOT NULL,
ID_SUBASTA INTEGER NOT NULL,
PUJA DOUBLE NOT NULL,
FECHA TIMESTAMP NOT NULL,
ESTADO VARCHAR(100),
CONSTRAINT PUJAS_PK PRIMARY KEY (ID),
CONSTRAINT SUBASTAS_FK FOREIGN KEY (ID_SUBASTA) REFERENCES SUBASTAS (ID)
);